<x-app-layout>
    <div class="page-frame">
        <section class="flex flex-col justify-between gap-8 border-b border-[#e5dfd4] pb-10 lg:flex-row lg:items-end">
            <div><p class="eyebrow">Bricofy · poste de pilotage</p><h1 class="display-title mt-4">Faire grandir la confiance, une mission à la fois.</h1><p class="mt-5 max-w-2xl text-base leading-7 text-[#6F6862]">Une lecture calme de la plateforme : les personnes qui arrivent, les projets qui avancent et les signaux qui méritent votre attention.</p></div>
            <div class="text-left lg:text-right"><p class="text-sm text-[#6F6862]">Aujourd’hui</p><p class="mt-1 font-serif text-2xl">{{ now()->format('d F Y') }}</p></div>
        </section>

        <section class="grid gap-8 py-10 lg:grid-cols-[1fr_0.62fr]">
            <div class="surface p-7 sm:p-9"><div class="flex items-end justify-between"><div><p class="eyebrow">La plateforme en mouvement</p><h2 class="mt-2 font-serif text-2xl">Les chiffres qui racontent le réseau</h2></div><span class="text-sm text-[#869B7E]">Vue globale</span></div><div class="mt-9 grid gap-8 sm:grid-cols-2"><div class="border-l-4 border-[#7F2020] pl-5"><p class="text-sm text-[#6F6862]">Clients actifs</p><p class="mt-2 font-serif text-4xl">{{ $nombreClients }}</p></div><div class="border-l-4 border-[#869B7E] pl-5"><p class="text-sm text-[#6F6862]">Prestataires</p><p class="mt-2 font-serif text-4xl">{{ $nombrePrestataires }}</p></div><div class="border-l-4 border-[#C9CAAC] pl-5"><p class="text-sm text-[#6F6862]">Missions déposées</p><p class="mt-2 font-serif text-4xl">{{ $nombreMissions }}</p></div><div class="border-l-4 border-[#2F2926] pl-5"><p class="text-sm text-[#6F6862]">Offres échangées</p><p class="mt-2 font-serif text-4xl">{{ $nombreOffres }}</p></div></div></div>
            <div class="relative min-h-[300px] overflow-hidden bg-[#2F2926] p-7 text-white sm:p-9"><img src="{{ asset('images/heroes/admin-team.jpg') }}" alt="Équipe qui coordonne des projets" class="absolute inset-0 h-full w-full object-cover opacity-30"><div class="absolute inset-0 bg-[#2F2926]/80"></div><div class="relative"><p class="eyebrow !text-[#C9CAAC]">À surveiller</p><p class="mt-6 font-serif text-3xl leading-tight">{{ $nombreEvaluations }} évaluations déposées par la communauté.</p><p class="mt-5 text-sm leading-6 text-white/65">Chaque retour nourrit la qualité des rencontres et aide les bons profils à émerger.</p><a href="{{ route('admin.evaluations.index') }}" class="mt-8 inline-block border-b border-[#C9CAAC] pb-1 text-sm font-bold text-[#C9CAAC]">Lire les évaluations →</a></div></div>
        </section>

        <section class="surface overflow-hidden"><div class="flex flex-col gap-3 border-b border-[#e5dfd4] p-6 sm:flex-row sm:items-end sm:justify-between sm:p-8"><div><p class="eyebrow">Le signal humain</p><h2 class="mt-2 font-serif text-2xl">Dernières évaluations</h2></div><a href="{{ route('admin.evaluations.index') }}" class="text-sm font-bold text-[#7F2020]">Ouvrir le registre →</a></div>@forelse($evaluations as $evaluation)<div class="grid gap-4 border-b border-[#e5dfd4] p-6 last:border-0 sm:grid-cols-[0.8fr_0.8fr_1.5fr_0.35fr_0.5fr] sm:items-center sm:p-8"><div><p class="text-xs uppercase tracking-[0.14em] text-[#869B7E]">Client</p><p class="mt-1 font-semibold">{{ $evaluation->client->name ?? 'N/A' }}</p></div><div><p class="text-xs uppercase tracking-[0.14em] text-[#869B7E]">Prestataire</p><p class="mt-1 font-semibold">{{ $evaluation->prestataire->name ?? 'N/A' }}</p></div><div><p class="text-xs uppercase tracking-[0.14em] text-[#869B7E]">Mission</p><p class="mt-1 text-sm text-[#6F6862]">{{ $evaluation->mission->titre ?? 'N/A' }}</p></div><div><p class="text-xs uppercase tracking-[0.14em] text-[#869B7E]">Note</p><p class="mt-1 font-serif text-xl text-[#7F2020]">{{ $evaluation->note }}/5</p></div><div class="text-sm text-[#6F6862]">{{ $evaluation->created_at?->format('d/m/Y') }}</div></div>@empty<div class="p-10 text-center font-serif text-xl">Aucune évaluation pour le moment.</div>@endforelse</section>
    </div>
</x-app-layout>
